apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: node-aws-docker
  region: us-east-1
vpc:
  id: "vpc-cba1f3ad"
  subnets:
    private:
      us-east-1a:
        id: “subnet-cb5b6a90”
      us-east-1c:
        id: “subnet-2ec9f303s”
nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 3
    privateNetworking: true
